R"((\n)|)" // NewLine
R"((//[^\n]*)|)" // singleLineComment
R"((/\*[\s\S]*?(?:\*/|$))|)" // multiLineComment
R"(([ \t\r\f\v]+)|)" // whitespace
R"((\.?[0-9](?:[eE][+-]|\.|[0-9a-zA-Z_])*)|)" // PPNumber
R"((auto(?![_a-zA-Z0-9]))|)" // Auto
R"((break(?![_a-zA-Z0-9]))|)" // Break
R"((case(?![_a-zA-Z0-9]))|)" // Case
R"((char(?![_a-zA-Z0-9]))|)" // Char
R"((const(?![_a-zA-Z0-9]))|)" // Const
R"((continue(?![_a-zA-Z0-9]))|)" // Continue
R"((default(?![_a-zA-Z0-9]))|)" // Default
R"((do(?![_a-zA-Z0-9]))|)" // Do
R"((double(?![_a-zA-Z0-9]))|)" // Double
R"((else(?![_a-zA-Z0-9]))|)" // Else
R"((enum(?![_a-zA-Z0-9]))|)" // Enum
R"((extern(?![_a-zA-Z0-9]))|)" // Extern
R"((float(?![_a-zA-Z0-9]))|)" // Float
R"((for(?![_a-zA-Z0-9]))|)" // For
R"((goto(?![_a-zA-Z0-9]))|)" // Goto
R"((if(?![_a-zA-Z0-9]))|)" // If
R"((int(?![_a-zA-Z0-9]))|)" // Int
R"((long(?![_a-zA-Z0-9]))|)" // Long
R"((register(?![_a-zA-Z0-9]))|)" // Register
R"((return(?![_a-zA-Z0-9]))|)" // Return
R"((short(?![_a-zA-Z0-9]))|)" // Short
R"((signed(?![_a-zA-Z0-9]))|)" // Signed
R"((sizeof(?![_a-zA-Z0-9]))|)" // Sizeof
R"((static(?![_a-zA-Z0-9]))|)" // Static
R"((struct(?![_a-zA-Z0-9]))|)" // Struct
R"((switch(?![_a-zA-Z0-9]))|)" // Switch
R"((typedef(?![_a-zA-Z0-9]))|)" // Typedef
R"((union(?![_a-zA-Z0-9]))|)" // Union
R"((unsigned(?![_a-zA-Z0-9]))|)" // Unsigned
R"((void(?![_a-zA-Z0-9]))|)" // Void
R"((volatile(?![_a-zA-Z0-9]))|)" // Volatile
R"((while(?![_a-zA-Z0-9]))|)" // While
R"((\.\.\.)|)" // DotDotDot
R"((;)|)" // Semicolon
R"((\[)|)" // OpenSquare
R"((\])|)" // CloseSquare
R"((\()|)" // OpenParen
R"((\))|)" // CloseParen
R"((\.)|)" // Dot
R"((->)|)" // Arrow
R"((~)|)" // Inv
R"((\+\+)|)" // Inc
R"((--)|)" // Dec
R"((&&)|)" // AndAnd
R"((&=)|)" // AndAssign
R"((&)|)" // And
R"((\*=)|)" // StarAssign
R"((\*)|)" // Star
R"((-)|)" // Minus
R"((!=)|)" // NotAssign
R"((!)|)" // Not
R"((/=)|)" // DivAssign
R"((/)|)" // Div
R"((%=)|)" // ModAssign
R"((%)|)" // Mod
R"((\+=)|)" // PlusAssign
R"((\+)|)" // Plus
R"((<<=)|)" // ShiftLeftAssign
R"((<<)|)" // ShiftLeft
R"((>>=)|)" // ShiftRightAssign
R"((>>)|)" // ShiftRight
R"((<=)|)" // LessEq
R"((<)|)" // Less
R"((>=)|)" // GrEq
R"((>)|)" // Gr
R"((==)|)" // EqEq
R"((\^=)|)" // XorAssign
R"((\^)|)" // Xor
R"((\|\|)|)" // OrOr
R"((\|=)|)" // OrAssign
R"((\|)|)" // Or
R"((\?)|)" // Query
R"((:)|)" // Colon
R"((=)|)" // Assign
R"((,)|)" // Comma
R"((##)|)" // HashHash
R"((#)|)" // Hash
R"((L?'(?:[^'\n\\]|\\(?:x[0-9a-fA-F]+|[0-7]{1,3}|['"?\\abfnrtv]))*(?:'|$))|)" // CharacterConstant
R"((L?".*?(?:"|$))|)" // StringLiteral
R"(([_a-zA-Z][_a-zA-Z0-9]*)|)" // Identifier
R"((.))" // NonWhiteSpace
