std::regex(R"(^\n)"), // NewLine
std::regex(R"(^//[^\n]*)"), // singleLineComment
std::regex(R"(^/\*[\s\S]*?(?:\*/|$))"), // multiLineComment
std::regex(R"(^[ \t\r\f\v]+)"), // whitespace
std::regex(R"(^\.?[0-9](?:[eE][+-]|\.|[0-9a-zA-Z_])*)"), // PPNumber
std::regex(R"(^auto(?![_a-zA-Z0-9]))"), // Auto
std::regex(R"(^break(?![_a-zA-Z0-9]))"), // Break
std::regex(R"(^case(?![_a-zA-Z0-9]))"), // Case
std::regex(R"(^char(?![_a-zA-Z0-9]))"), // Char
std::regex(R"(^const(?![_a-zA-Z0-9]))"), // Const
std::regex(R"(^continue(?![_a-zA-Z0-9]))"), // Continue
std::regex(R"(^default(?![_a-zA-Z0-9]))"), // Default
std::regex(R"(^do(?![_a-zA-Z0-9]))"), // Do
std::regex(R"(^double(?![_a-zA-Z0-9]))"), // Double
std::regex(R"(^else(?![_a-zA-Z0-9]))"), // Else
std::regex(R"(^enum(?![_a-zA-Z0-9]))"), // Enum
std::regex(R"(^extern(?![_a-zA-Z0-9]))"), // Extern
std::regex(R"(^float(?![_a-zA-Z0-9]))"), // Float
std::regex(R"(^for(?![_a-zA-Z0-9]))"), // For
std::regex(R"(^goto(?![_a-zA-Z0-9]))"), // Goto
std::regex(R"(^if(?![_a-zA-Z0-9]))"), // If
std::regex(R"(^int(?![_a-zA-Z0-9]))"), // Int
std::regex(R"(^long(?![_a-zA-Z0-9]))"), // Long
std::regex(R"(^register(?![_a-zA-Z0-9]))"), // Register
std::regex(R"(^return(?![_a-zA-Z0-9]))"), // Return
std::regex(R"(^short(?![_a-zA-Z0-9]))"), // Short
std::regex(R"(^signed(?![_a-zA-Z0-9]))"), // Signed
std::regex(R"(^sizeof(?![_a-zA-Z0-9]))"), // Sizeof
std::regex(R"(^static(?![_a-zA-Z0-9]))"), // Static
std::regex(R"(^struct(?![_a-zA-Z0-9]))"), // Struct
std::regex(R"(^switch(?![_a-zA-Z0-9]))"), // Switch
std::regex(R"(^typedef(?![_a-zA-Z0-9]))"), // Typedef
std::regex(R"(^union(?![_a-zA-Z0-9]))"), // Union
std::regex(R"(^unsigned(?![_a-zA-Z0-9]))"), // Unsigned
std::regex(R"(^void(?![_a-zA-Z0-9]))"), // Void
std::regex(R"(^volatile(?![_a-zA-Z0-9]))"), // Volatile
std::regex(R"(^while(?![_a-zA-Z0-9]))"), // While
std::regex(R"(^\.\.\.)"), // DotDotDot
std::regex(R"(^;)"), // Semicolon
std::regex(R"(^\[)"), // OpenSquare
std::regex(R"(^\])"), // CloseSquare
std::regex(R"(^\()"), // OpenParen
std::regex(R"(^\))"), // CloseParen
std::regex(R"(^\.)"), // Dot
std::regex(R"(^->)"), // Arrow
std::regex(R"(^~)"), // Inv
std::regex(R"(^\+\+)"), // Inc
std::regex(R"(^--)"), // Dec
std::regex(R"(^&&)"), // AndAnd
std::regex(R"(^&=)"), // AndAssign
std::regex(R"(^&)"), // And
std::regex(R"(^\*=)"), // StarAssign
std::regex(R"(^\*)"), // Star
std::regex(R"(^-)"), // Minus
std::regex(R"(^!=)"), // NotAssign
std::regex(R"(^!)"), // Not
std::regex(R"(^/=)"), // DivAssign
std::regex(R"(^/)"), // Div
std::regex(R"(^%=)"), // ModAssign
std::regex(R"(^%)"), // Mod
std::regex(R"(^\+=)"), // PlusAssign
std::regex(R"(^\+)"), // Plus
std::regex(R"(^<<=)"), // ShiftLeftAssign
std::regex(R"(^<<)"), // ShiftLeft
std::regex(R"(^>>=)"), // ShiftRightAssign
std::regex(R"(^>>)"), // ShiftRight
std::regex(R"(^<=)"), // LessEq
std::regex(R"(^<)"), // Less
std::regex(R"(^>=)"), // GrEq
std::regex(R"(^>)"), // Gr
std::regex(R"(^==)"), // EqEq
std::regex(R"(^\^=)"), // XorAssign
std::regex(R"(^\^)"), // Xor
std::regex(R"(^\|\|)"), // OrOr
std::regex(R"(^\|=)"), // OrAssign
std::regex(R"(^\|)"), // Or
std::regex(R"(^\?)"), // Query
std::regex(R"(^:)"), // Colon
std::regex(R"(^=)"), // Assign
std::regex(R"(^,)"), // Comma
std::regex(R"(^##)"), // HashHash
std::regex(R"(^#)"), // Hash
std::regex(R"(^L?'(?:[^'\n\\]|\\(?:x[0-9a-fA-F]+|[0-7]{1,3}|['"?\\abfnrtv]))*(?:'|$|\n))"), // CharacterConstant
std::regex(R"(^L?"(?:[^"\n\\]|\\(?:x[0-9a-fA-F]+|[0-7]{1,3}|['"?\\abfnrtv]))*(?:"|$|\n))"), // StringLiteral
std::regex(R"(^[_a-zA-Z][_a-zA-Z0-9]*)"), // Identifier
std::regex(R"(^.)") // NonWhiteSpace
